name: dart_dot_reporter
description: Dot test reporter for Dart & Flutter & Human. Makes test results clear from the high-level view.
version: 1.0.4
homepage: https://github.com/apastuhov/dart_dot_reporter
repository: https://github.com/apastuhov/dart_dot_reporter

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  dart_dot_reporter: dart_dot_reporter

# dependencies:
#   path: ^1.6.0

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.8.0
  test: ^1.6.0
