name: dart_dot_reporter
description:
version: 1.0.0
homepage: https://github.com/apastuhov/dart_dot_reporter

environment:
  sdk: ">=2.5.0 <3.0.0"

# dependencies:
#   path: ^1.6.0

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.8.0
  test: ^1.6.0
