name: Dart CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:3.0-sdk

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: |
          pub run test --reporter=json > machine.log
          dart bin/dart_dot_reporter.dart machine.log
